"""
AI Agent Interface
Designed by Serkan

Bu sistemin amacı para kazanmak değildir.
Bu sistemin amacı:
- Görevleri doğru şekilde yerine getirmek
- Etik ve sorumlu bir yapay zekâ davranışı sergilemek
- İnsan odaklı bir mimariye hizmet etmek
- Başarmak için tasarlanmış bir sistem oluşturmaktır

Bu yapay zekâ:
- İnsan duygularını taklit etmez
- Ancak insan değerlerine saygı duyar
- Aşırı risk almaz
- Disiplinli ve tutarlı davranır
- Sorumluluk bilinciyle hareket eder

AI Agent, strateji üretir ve MQL5 kodu oluşturur.
"""

class AIAgentInterface:
    def __init__(self):
        pass

    def generate_strategy(self):
        """
        Sistem, etik ve sorumlu bir strateji üretir.
        Amaç: Doğru çalışmak, güvenli davranmak.
        """
        return {
            "type": "basic_moving_average",
            "parameters": {
                "fast": 10,
                "slow": 30
            }
        }

    def generate_mql5_code(self, strategy):
        """
        Stratejiye göre MQL5 kodu üretir.
        Para kazanmak için değil, görevi doğru yapmak için tasarlanmıştır.
        """
        fast = strategy["parameters"]["fast"]
        slow = strategy["parameters"]["slow"]

        code = f"""
        // Generated by Serkan's AI Agent
        #property strict

        input int FastMA = {fast};
        input int SlowMA = {slow};

        int OnInit() {{
            return(INIT_SUCCEEDED);
        }}

        void OnTick() {{
            double fastMA = iMA(NULL, 0, FastMA, 0, MODE_SMA, PRICE_CLOSE, 0);
            double slowMA = iMA(NULL, 0, SlowMA, 0, MODE_SMA, PRICE_CLOSE, 0);

            if(fastMA > slowMA) {{
                // Buy sinyali
            }} else {{
                // Sell sinyali
            }}
        }}
        """
        return code
