"""
AI Agent Interface
Designed by Serkan

Bu modül, yapay zekâ strateji üreticisinin arayüzüdür.
Gerçek bir AI modeli ile entegre edilebilir.
Şimdilik simülasyon modunda çalışır.
"""

class AIAgentInterface:
    def __init__(self):
        self.model_loaded = True

    def generate_strategy(self):
        """
        AI tarafından strateji üretimi.
        Gerçek sistemde burada model çalışır.
        Şimdilik güvenli bir örnek strateji döner.
        """
        return {
            "symbol": "EURUSD",
            "action": "BUY",
            "confidence": 0.72,
            "stop_loss": 0.0015,
            "take_profit": 0.0025
        }

    def generate_mql5_code(self, strategy):
        """
        Stratejiye göre MQL5 kodu üretir.
        Gerçek sistemde AI kod üretir.
        Şimdilik güvenli bir örnek EA kodu döner.
        """

        symbol = strategy.get("symbol", "EURUSD")
        action = strategy.get("action", "BUY")
        sl = strategy.get("stop_loss", 0.0015)
        tp = strategy.get("take_profit", 0.0025)

        mql5_code = f"""
//+------------------------------------------------------------------+
//| Expert Advisor generated by Serkan's AI                          |
//+------------------------------------------------------------------+
#property strict

input string InpSymbol = "{symbol}";
input double StopLoss = {sl};
input double TakeProfit = {tp};

int OnInit()
  {{
   Print("EA initialized for symbol: ", InpSymbol);
   return(INIT_SUCCEEDED);
  }}

void OnTick()
  {{
   double lot = 0.01;
   int ticket;

   if(PositionsTotal() == 0)
     {{
      ticket = OrderSend(InpSymbol, OP_{action}, lot, Ask, 10, 
                         Ask - StopLoss, Ask + TakeProfit, 
                         "AI Trade", 0, 0, clrBlue);

      if(ticket < 0)
         Print("OrderSend failed: ", GetLastError());
     }}
  }}
"""
        return mql5_code
